name: ARM build

on:
  push:
    branches: [ "main", "dev5" ]
  pull_request:
    branches: [ "main", "dev5" ]

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    container: andywick/arkime-build-al2023-arm64:5.0.0-3

    steps:
    - name: install
      run: |
        yum -y install git wget sudo

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: easybutton
      run: |
        ln -s /thirdparty .
        ./easybutton-build.sh

    - name: tests
      run: (cd tests; ./tests.pl)
