name: ARM build

on:
  push:
    branches: [ "main", "dev5" ]
  pull_request:
    branches: [ "main", "dev5" ]

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    container: public.ecr.aws/amazonlinux/amazonlinux:2023

    steps:
    - name: install
      run: |
        yum -y install git wget sudo

    - uses: actions/checkout@v3

    - name: easybutton
      run: ./easybutton-build.sh

    - name: tests
      run: (cd tests; ./tests.pl)
