name: "Build"

on:
  push:
    branches: [ "main", "dev5" ]
  pull_request:
    branches: [ "main", "dev5" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.14

    steps:
    - name: install git
      run: |
        apk add --no-cache curl bash sudo git
        git config --global --add safe.directory `pwd`

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: build
      run: |
        (cd / ; curl https://s3.amazonaws.com/files.molo.ch/snfmin.tar.gz | tar -zxvf -)
        ./easybutton-build.sh --rminstall --kafka
        (cd tests ; ./tests.pl)

    - name: install
      run: |
        export PATH=/opt/arkime/bin:$PATH
        make install
        npm run lint
